language: android
sudo: required
jdk: oraclejdk8
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - ANDROID_API_LEVEL=27
  - ANDROID_BUILD_TOOLS=27.0.3
android:
 components:
 - tools
 - platform-tools
 - build-tools-$ANDROID_BUILD_TOOLS
 - android-$ANDROID_API
 - extra-google-m2repository
 - extra-android-m2repository # for design library
 - addon-google_apis-google-19 # google play services
 licenses:
 - '.+'
before_install:
- openssl aes-256-cbc -K $encrypted_3f5ddde1a2e2_key -iv $encrypted_3f5ddde1a2e2_iv
  -in wear/horlogo-release-enc.keystore -out wear/horlogo-release.keystore -d
- mkdir "$ANDROID_HOME/licenses" || true
- yes | sdkmanager "platforms;android-$ANDROID_API_LEVEL"
- echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
- echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
script:
- "./gradlew build check"
deploy:
  provider: releases
  api_key:
    secure: DogUXjxmf2vpzes5ybBm8kUh3gLdcFcUEcYEu7GKwIwW2dIueA145V5/K8g4cF7/IcMwPAl3psK36jKQCINzKhR3FpiYT44UkFE77OeNB1Z1gvy4a17ptgfBho3JkfmwqxAop0lFWUVZliUNbqCN6I0y9z9Zw2mJa4bc7Ja/R8GoHV6P/1F9KHrkK8qRAEDkIfubpmUrA+SEcZWuc8eALUVjH/tRHjUpV7ax41Ufk3FD11JDH1/Ry+dHXvZ7n0AhR3hYverVXaU1RIFu1bpYZMXbk6rNXzwFNMWMtWsjmz1Ce1vEzCmLU7jvccjtnAec4nXVrk0v2vjGG0tHQ6n0QoiEN5mKJ1iHCgH8A4woVb4ZtFFTSO2rSwVQ0p+/SsOoTOUqOJMxCjcV/mkDS/O0JMDurQDVyHqXm6Y3MY1mnJFzaQkKKEdP8jWSacKzYFW+Ble999n7nIu/9C28BIB4bWQoQFaops+PuQWitqPScqRxTlNUufbcYD+W8tAnRy6ulwFCoWOx920Y77HNFtTgLczbJLfOe8DqY3kqX94evgXLS32cZxkuEM+jPabXo74pZW6sCJAZOydy7QU10FeZlHvFnjw7s+1Nt13ouEZ2IKa2Z7Ye/m6YB0DJ6LK3FeK96BgA+5x/y1i9e2OB5VjM9hj8cGglM+ePr712cvFYwX4=
  file: wear/build/outputs/apk/wear-release.apk
  on:
    repo: AChep/horlogo
    tags: true
