package com.artemchep.horlogo

const val WATCH_COMPLICATION_FIRST = 101
const val WATCH_COMPLICATION_SECOND = 102
const val WATCH_COMPLICATION_THIRD = 103
const val WATCH_COMPLICATION_FOURTH = 104

/**
 * Array of IDs of all complications: [WATCH_COMPLICATION_FIRST], [WATCH_COMPLICATION_SECOND],
 * [WATCH_COMPLICATION_THIRD], [WATCH_COMPLICATION_FOURTH].
 */
val WATCH_COMPLICATIONS = intArrayOf(
        WATCH_COMPLICATION_FIRST,
        WATCH_COMPLICATION_SECOND,
        WATCH_COMPLICATION_THIRD,
        WATCH_COMPLICATION_FOURTH)
